### ISSUE TITLE
In favor of NULL

### ISSUE THREAD

**Issue by rcarver** [toml-lang/toml#146]
Here's an argument in favor of `NULL` values, as previously discussed and rejected in #30.

I believe that in configuring a system, the most important things are:
1. The set of available keys (and key groups).
2. An understanding of what those keys do, and as necessary, the type of value expected.

Therefore, I think it's important to be able to define, and comment, keys for which you don't yet have a value. A TOML document should be able to act as a specification for the possible configuration. It may be preferable not to define a value in the TOML config - say, in order to set a reasonable default at runtime. But, it is important to specify that such a value _can_ be set. This is typically done by commenting out the key, and that seems ugly.

Put another way, it's the difference between `hash[key].nil?` and `hash.key?(key)` in Ruby or `hash[key] == null` and `hash[key] === undefined` in JavaScript. I think it's important, to aid in the downstream validation and use of the data provided by a TOML document.

Disclosure: my own take of this whole situation is [levels](https://github.com/rcarver/levels), which defines a way to merge multiple inputs into a final configuration. When adding TOML support in rcarver/levels#3 I realized that we have a fundamental disagreement here. In all other ways, TOML is the ideal format for levels configuration.

As far as the syntax, I don't have a strong opinion. I think I'm leaning toward a lack of value because it doesn't introduce a new keyword, and it resembles what you'd do in bash.

```
this_is_null = 
```

**Comment by bitc** [comment]
Here's a trick that wasn't immediately obvious to me for those of you who need some NULL-like value:

Use `false`

For example:

`a.toml`:
```toml
timeout = 1000
```

`b.toml`:
```toml
timeout = false
```

Now why not just leave out `timeout` completely if you want to disable the timeout? One reason is you may want to prefer to be explicit. Another reason is you might have some override system. Example:

```toml
# Global settings
timeout = 1000

# Override settings for admin users
[admin]
timeout = false
```

Of course, this trick won't work for boolean fields, but arguably you should never make these nullable anyway since it is too confusing ("What's the difference between `false` and `null`?")

**Comment by ChristianSi** [comment]
@matthew-dean: I wouldn't say so. A SQL table will be usually serialized as an array of tables in TOML; absence of a key-value pair in a table signals that the value is NULL. TOML is flexible where SQL is strict (there is no need to repeat the same keys in *every* table of an array), hence no explicit NULL is needed. Other DB data can be treated in a similar matter.

Strict round-trip compatibility from and to JSON is not possible, but that's also due to other factors, such as TOML having datetimes which JSON lacks. As for data being exportable to JSON, but not TOML, I think there will rarely be issues. The most problematic case is probably a simple array (of values) that includes some NULL values, but I think such data will not be all that common in well-structured data sets. If it occurs, it's probably best discussed on a case-by-case basis (some kind of sentinel value might be usable).

**Comment by pedromorgan** [comment]
Can use TOML because of null "problem", in my case its dumping db tables (see @ChristianSi  comment above)

**Comment by eksortso** [comment]
> Can't use TOML because of null "problem", in my case its dumping db tables (see @ChristianSi comment above)

We can't tell what's going on with your program, because you didn't give us any code examples. So we can't offer you much advice.

But pertinent to @ChristianSi's comment, let's say you have a table that looks like this:

| id | name   | stuff              |
| -- | ------ | ------------------ |
|  0 | Naive  | One umlaut ignored |
|  1 | Grotus | _NULL_             |

What do your rows look like in your program?

If they look like this, then of course you're going to have problems.

```toml
rows = [
    [0, "Naive", "One umlaut ignored"],
    [1, "Grotus", ],  # TOML does not permit NULLs
]
```

But if you reread the comment, then you'll see that this is the proper way to represent rows.

```toml
rows = [
    {id = 0, name = "Naive", stuff = "One umlaut ignored"},
    {id = 1, name = "Grotus"},
]
```
