### ISSUE TITLE
Preserving order

### ISSUE THREAD

**Issue by beygi** [toml-lang/toml#162]
we have a discussion here about preserving orders of hashes : 
https://github.com/uiri/toml/pull/2
its better to describe this in specification , my suggestion is : yes , key orders and group key orders must be preserved in parsers implementation

**Comment by JavaScriptDude** [comment]
Just for posterity, the fact that it is called `Table` infers that it is ordered as tables are ordered. If its unordered it should be called a dictionary. I have heard several high visibility developers slamming TOML because of this exact ambiguity and they have vowed to never use it again, which I find silly but it happens.

Why not just start calling it a dictionary instead of table?

**Comment by eksortso** [comment]
@JavaScriptDude You're missing some context here. In JavaScript, objects are unordered by default. In Python since 3.7, dictionaries use insertion order, like Maps in JavaScript. In relational databases, tables are unordered by default.

The context matters, and in TOML the order of tables is said _not to be guaranteed_. That doesn't mean, though, that a parser can't provide an option to use the appropriate containers to enforce insertion ordering, so long as that behavior is documented. Such behavior is outside the scope of the TOML spec, but it doesn't violate the spec.

So, I must ask: in what context are tables, as you and your coworkers understand the term, ordered by default?

**Comment by JavaScriptDude** [comment]
I come from a perspective of intuitiveness where I originally got into programming after being an Lotus / Excel Guru way back in the day. 

[Wikipedia definition](https://en.wikipedia.org/wiki/Table_(information)) of table: "A table consists of an ordered arrangement of rows and columns".

I guess as long as the documentation makes it super clear in all appropriate places that a table is, for all intents and purposes unordered, that would suffice.

I do really like TOML and use it daily.

**Comment by eksortso** [comment]
@JavaScriptDude Glad that you're getting good use out of TOML! Thanks for sharing your experience. I suppose "obvious" is a bold claim for us to make, but ultimately it depends on users reading the spec at least once, and on us making the important things stand out.

Also, thanks for sharing the complaint. I just now listened to that particular part of their presentation. They complained and hurled abuse at TOML, but the problems they experienced were all on them, because they assumed what they shouldn't have.

This issue is closed, so if you wish to suggest a way to guarantee in part that keys in a TOML document are ordered as written, open a new issue. We're in the process of getting v1.1.0 out the door, so it may take some time to revisit this. But I would welcome the conversation.
