### ISSUE TITLE
Version Tag

### ISSUE THREAD

**Issue by valarauca** [toml-lang/toml#239]
Going forward the file's layout system will change over time, and the standard will change.

Therefore shouldn't it be necessary to add a 

     version=String;

Say before or after title? Allowing for the parser to know what version of the standard it is working with. This will also allow domain specific extensions of the layout, promoting further use.

**Comment by mojombo** [comment]
Since TOML is designed to be a config format, I don't think the actual TOML document needs to state the version of TOML it is using. This is because the application that reads the TOML document already knows what version it supports, and presumably will communicate this to the end user that is writing the config file. If, at some point in the future, the presence of a version in the document becomes useful, I'd lean towards a shebang-style comment instead of a TOML value. But for now, I call YAGNI.
