### ISSUE TITLE
multi-line literals have platform-specific meaning

### ISSUE THREAD

**Issue by skybrian** [toml-lang/toml#281]
Hi, this is just a drive-by comment but I thought I'd point this out:

With respect to multi-line literals, the README says:

"TOML parsers should feel free to normalize newline to whatever makes sense for their platform."

It seems like this would be a problem for cross-platform code? Suppose someone writes a config file on Unix and copies it to Windows, or vice-versa. Now all the multi-line strings contain slightly different data! It seems like collaborating via source control will be harder as well.

Perhaps TOML should aim for files having the same meaning regardless of which computer you use to parse them? Also, running a config file though dos2unix or unix2dos should have no effect on the data described in the file.

(Or perhaps I've missed something obvious that should be documented better.)

**Comment by BurntSushi** [comment]
Files created on Windows use CRLF. Files created on UNIX like systems will use LF. The TOML spec defines a "new line" token to be either CRLF or LF, which means multiline strings will retain their semantic value regardless of whether you use CRLF or LF.

The line you quoted simply means that parsers can choose to normalize these line endings when handing the data to the client of the parser, although it is not required. I can't think of any obvious drawbacks to this approach and I don't see how this changes meaning. As I understand it, Python's "universal line mode" does something similar.

Running `dos2unix` or `unix2dos` should not change the semantic meaning of any TOML document.

**Comment by skybrian** [comment]
Here's what Python's universal newline support says:

"Any line ending in the input file will be seen as a '\n' in Python, so little other code has to change to handle universal newlines." [1]

That seems a lot clearer than the TOML specification. I'm not sure what you mean by semantic meaning or by "normalize"; what I mean is the sequence of Unicode code points seen by the parser's client when the parser hands it a string. If the representation isn't specified like in Python then different parsers can return different code points.

[1] https://www.python.org/dev/peps/pep-0278/

**Comment by BurntSushi** [comment]
> I'm not sure what you mean by "semantic meaning"

TOML gives special significance to the first new line character of a multiline string (i.e., it is trimmed). That is, multiline strings always have the same number of lines, regardless of whether CRLF or LF is used and regardless of which platform you're on.

> what I mean is the sequence of Unicode code points seen by the parser's client when the parser hands it a string. If the representation isn't specified like in Python then different parsers can return different code points.

Yes, I believe that is true. That is my current understanding of the spec anyway. I think we put that in there so that TOML *encoders* could Do The Right Thing for their platform if they wanted to. Python doesn't have any "write" universal line support, but if a parser normalizes line endings in multiline strings, then those strings can be written back to a TOML document correctly.

For example, if a multiline string contains the *bytes* `a\r\nb`, and it is deserialized and serialized on a *nix platform with a parser that normalizes new line characters, then it will be written as `a\nb`. Doing the same on a Windows platform yields `a\r\nb`. If parsers weren't allowed to normalize lines, then `a\r\nb` would be serialized on *nix platforms, assuming no other intervention from the client.

Maybe a different approach to this is to just say, "TOML encoders may normalize new lines when writing."

Another approach is to copy Python universal line support directly. But then Windows users will have to deal with `\n` when serializing TOML.

Yet another approach is to say that TOML sees `CRLF` and `LF` as line endings, but no other normalization is done.

I don't know which of these is the best solution.

**Comment by ChristianSi** [comment]
I'd propose to just change the sentence in question from

> TOML parsers should feel free to normalize newline to whatever makes sense for their platform.

to

> TOML parsers and writers should feel free to normalize newline to whatever makes sense for their platform.

I think that should be sufficient to address these issues.

I guess "what makes most sense" will generally be `\n` in-memory (as read by parsers), `\r\n` on Unix, and `\n`, but parser/writer implementors will be able to decide that best.

**Comment by mojombo** [comment]
@ChristianSi I'm unconvinced that the TOML spec needs to say anything about how a TOML file might be *written*. Writers should be able to write the file any way they wish as long as they produce a valid TOML document. For various reasons they may want to alter a string during a round-trip, or not. I don't think it's the TOML spec's place to say.

@skybrian I like the spec the way it is now. Multi-line TOML strings will contain whatever line endings the file actually contains. This allows you to deliberately represent any UTF-8 byte sequence you wish (whereas a guaranteed conversion to \n would not). Most parsers will probably default to normalizing line-endings to that preferred by the platform but also allow for reading the data without munging. Just like Python. TOML's job is to unambiguously hold the data as you specify it. The parser's job is to give it to you, the programmer, in a way that makes it easy to use.

**Comment by skybrian** [comment]
I was thinking about how to use TOML as a portable, readable serialization format. I guess for people concerned about round-tripping strings, writing out either single-line strings or as a basic multi-line strings where each line ends with either "\r\n\" or "\n\" as appropriate should survive in any parser that follows the spec. Leading whitespace could be represented as "\n  \" at the end of the previous line.

If you know which parser will be reading the file and what its normalization policy is then regular multi-line strings could be used.
