### ISSUE TITLE
Are comments OK in multiline arrays?

### ISSUE THREAD

**Issue by takluyver** [toml-lang/toml#340]
The spec says:

> Arrays can also be multiline. So in addition to ignoring whitespace, arrays also ignore newlines between the brackets. 

With an example:

```
arr8 = [
  1,
  2, # this is ok
]
```

The description doesn't appear to allow comments in multiline arrays (ignoring whitespace and newlines doesn't imply ignoring comments). I'm not sure whether the example is supposed to be valid as written, or whether the comment is for illustration and should be removed.

The description of comments being "the rest of the line" implies that this is valid, but that could also be read to allow comments in multiline strings, which is (I hope) not the case.

**Comment by BurntSushi** [comment]
There are no comments allowed in strings.

Comments are allowed in multiline arrays. The example is valid.

Personally, I think the spec is pretty clear (all examples are valid TOML unless stated otherwise). But if you'd like to submit a small PR tweaking the language to be clearer then i'd probably be OK with that.

**Comment by takluyver** [comment]
Thanks! I've opened #341 to be explicit about this.
