### ISSUE TITLE
Should "linefeed" be "line feed"?

### ISSUE THREAD

**Issue by aloisdg** [toml-lang/toml#417]
Hello,

I think I found a typo in the ReadMe file.

In the [String](https://github.com/toml-lang/toml/blob/master/README.md#string) section, we have:

```
\n         - linefeed        (U+000A)
```

I think, it should be:

```
\n         - line feed        (U+000A)
```

Also, [Wikipedia](https://en.wikipedia.org/wiki/Newline) uses "line feed" for the character "LF".

What do you think?

Cheers,

Related to #176 

PS: We could replace "tab" with "tabulation" too.

**Comment by eksortso** [comment]
Well, RFC 5234 uses both "line feed" and "linefeed". That's a
counter-argument against changing.

More to the point, how much does keeping it as "linefeed" or changing it to
"line feed" impact things?

**Comment by aloisdg** [comment]
And [w3](https://www.w3.org/TR/newline) use "line feed".

> More to the point, how much does keeping it as "linefeed" or changing it to "line feed" impact things?

Not so much. It feels more english and more coherent with "form feed".

**Comment by mojombo** [comment]
I like the single-word forms of things like linefeed and newline because they feel like single encapsulated concepts worthy of single word names. It also means I don't have to worry about any confusion that might arise from a human mind parsing a sentence wrong because the separated "line" or "feed" or whatnot fell in an unfortunate spot.
