### ISSUE TITLE
Add version type

### ISSUE THREAD

**Issue by emilmelnikov** [toml-lang/toml#451]
Since TOML is widely used for specifying software configurations, it makes sense to add a _Version_ type to the spec.

Example:
```toml
[project]
version = v1.2.4
```
The `v` prefix differentiates the version from a floating-point number and emphasizes the type of the value.

Although it is optional, libraries can compare version types according to the [Semantic Versioning](http://semver.org/) policy.

**Comment by TheElectronWill** [comment]
Why not just use a String ?

**Comment by emilmelnikov** [comment]
TOML already has first-class datetimes. I believe they have been added for clarity in configs and stronger type-checking in implementations. The same reasons go for the Version type.

Another useful addition might be the datetime _duration_, maybe something in the DNS zone file style: (`1h` or `3m`).

**Comment by TheElectronWill** [comment]
The problem with the version type is that it doesn't map to a "native" type. It maps to a String, that's it. And since everyone has a different version format I don't see what kind of checking the parser could do.

Also, if TOML adds a Version type, then a URL type is also needed, and a filename type, and a currency type, etc.

**Comment by emilmelnikov** [comment]
Yes, you are right, so this issue should be closed.
Also, version strings are actually _not_ simple: version requirements [Rust's Cargo package manager](http://doc.crates.io/specifying-dependencies.html) is the example.
