### ISSUE TITLE
Readme specification of keys is ambiguous

### ISSUE THREAD

**Issue by vmchale** [toml-lang/toml#464]
In the readme, it specifies bare keys as follows:

```markdown
Bare keys may only contain letters, numbers, underscores, and dashes `(A-Za-z0-9_-)`
```

This can be confusing, because, for example,

```toml
çe = "value"
```

is not considered valid TOML though I expected it to be. 

If possible, you should either:

1. Avoid specifying letters as `(A-Za-z)` and instead specify letters as "unicode letters and unicode nonspacing marks (to include dependent vowels such as བོ) and numbers as "unicode decimal digists".
2. Specify that letters  and numerals should be valid ASCII and that they may *not* be letters or numerals from utf8. 

Thanks!

**Comment by dtolnay** [comment]
Based on #283 and #337 it seems like the restriction to `A-Za-z0-9_-` is very intentional. I agree that "letter" is not the clearest way to specify `A-Za-z`, "number" is not the clearest way to specify `0-9`, and "dash" is not the clearest way to specify `-`.

Relevant PR on the Rust side: https://github.com/alexcrichton/toml-rs/pull/177

**Comment by ChristianSi** [comment]
Yes, the restriction is intentional. It would probably be better to rewrite the above as:

> Bare keys may only contain ASCII letters, ASCII digits, underscores, and hyphens `(A-Za-z0-9_-)`.

**Comment by mk-pmb** [comment]
Yes, "ASCII letter" is a better wording, especially considering that

> letters and numerals should be valid ASCII and that they may not be letters or numerals from utf8.

is useless because there would be no letters left, as ASCII is a true subset of utf8.
