### ISSUE TITLE
ABNF no longer works with APG

### ISSUE THREAD

**Issue by mojombo** [toml-lang/toml#502]
@pradyunsg I remember now why I didn't use any [incremental alternatives](https://tools.ietf.org/html/rfc5234#section-3.3) in the ABNF. It's because the APG parser that we reference doesn't seem to handle them. The APG parser was the only thing I could find that seemed to do approachable ABNF parsing so I was trying to keep it compliant to make testing of the grammar easier.

I much prefer the incremental alternative syntax, as it cleans things up quite nicely. I'll reach out the apg-js2 author and see if there's something we can do about it.

**Comment by pradyunsg** [comment]
> @pradyunsg I remember now why I didn't use any incremental alternatives in the ABNF. It's because the APG parser that we reference doesn't seem to handle them.

I was wondering -- how is there so much low hanging fruit.

> I'll reach out the apg-js2 author and see if there's something we can do about it.

That is probably a good idea.

**Comment by pradyunsg** [comment]
In case that doesn't come through, maybe there's merit in switching to EBNF? It's has an ISO document and there's definitely more parser generators out there which accept it.

**Comment by robmuh** [comment]
ABNF is the only acceptable [IETF standard] currently (if that is the standards body we are targeting). By the way, which is the likely direction?

On a side note, I have been using "Bill's ABNF" syntax checker for my [BaseML] stuff because I am thinking of an IETF submission (because the "markdown" [MIME submission] looks like it made it through that group already).

After I finish the BaseML reference parser/processor I would like to create an ABNF validation tool in Go and later Crystal. Is anyone aware of effort there? If we can identify a better validator (or create one) I think we can promote [ABNF over regular expressions] for more development as well as directly benefit the TOML project.

This parser is ancient and does not have support for `%x2000` and such. I have tried to locate Bill Fenner (who wrote it) to no avail. 

[MIME submission]: https://tools.ietf.org/html/rfc7764
[IETF standard]: https://tools.ietf.org/html/rfc5234
[BaseML]: https://github.com/knowledge-net/knowledge-net.github.io/blob/master/baseml/baseml.abnf
[ABNF over regular expressions]: http://knowledgenet.io/baseml/faq/#why-not-use-regular-expressions

**Comment by mojombo** [comment]
Just added this to the ABNF. We're back in business!

```
;; You can try out this grammar using http://instaparse.mojombo.com/
;; To do so, in the lower right, click on Options and change `:input-format` to
;; ':abnf'. Then paste this entire ABNF document into the grammar entry box
;; (above the options). Then you can type or paste a sample TOML document into
;; the beige box on the left. Tada!
```

Over time I'd like to adapt this tool to be TOML specific. Original code here: https://github.com/mhuebert/instaparse-live (though the last commit breaks everything, so I deployed the working version on my own subdomain).

**Comment by pradyunsg** [comment]
> Just added this to the ABNF. We're back in business!

Awesome! :)
