### ISSUE TITLE
Can toml use variables?

### ISSUE THREAD

**Issue by weichangdong** [toml-lang/toml#528]
```
dir=/tmp/
dir1={dir}dir1
dir2={dir}dir2
```
can toml reach this effect?

**Comment by eksortso** [comment]
It can't, and that was a deliberate design choice. Any logic, complicated or not, is best handled by the consumer of the TOML file. TOML doesn't handle that logic.

So in your case, you can configure the`dir` and its subdirectories in TOML, and then have your program read the TOML and compute the subdirectory paths.

```
# Here's an example. 
dir = '/tmp/'
subdir1 = "dir1"
subdir2 = "dir2"
```

You can also include comments in the TOML file so that the configuration entries make intuitive sense.

Hope that helps.

**Comment by weichangdong** [comment]
got it.3q.
