### ISSUE TITLE
Allow hexadecimal, binary and octal integer representations

### ISSUE THREAD

**Issue by amadawn** [toml-lang/toml#53]
In many areas (such as science and engineering) integer configuration values are very common. Having TOML support them would make the format a little more general and less web-centric.

**Comment by tshepang** [comment]
I am surprised that these aren't supported. We use JSON a lot at work, and I hate the standard for not supporting hex. We modified the JSON parser to accept that, which makes in not-JSON, but very very useful. We do some low-level bit-twiddling, and it really helps to see some stuff expressed in hex... decimal is serious incovenient at times.

I see some people talking about keeping TOML simple, but after reading the spec, there's stuff already far more complex than `0b 0o 0x` (e.g. dates and compact tables). The workaround of using strings is just too much of a hack.

**Comment by ChristianSi** [comment]
I can see that hex integers can be useful for various applications, but I wonder about octal and binary representations. Are there really any serious real-life use cases where they are more useful than their decimal or hex equivalents?

**Comment by tshepang** [comment]
I don't know. Selfish me is only interested in hex, but it really doesn't
hurt adding support for the other two.

**Comment by ChristianSi** [comment]
@tshepang: I think it does hurt adding features that aren't used, or that are used were rarely. Every new feature means a higher burden for all the implementors of the TOML language, so it's good to apply very strict "is still really needed?" checks before anything new goes in.

**Comment by tshepang** [comment]
let's just do hex then, since it's the most popular non-decimal format

**Comment by jakwings** [comment]
Are there any more common problems about v0.4.0? If no, I suggest reopening this issue.

Hex and octal are good. (hex > octal) Octal is mainly used to specify permissions, I guess?

**Comment by majewsky** [comment]
I would like to have these included as well, because of the specific domains where base-10 is strongly confusing. My strongest concern would be confusion to people not knowing about these special cases (C programmers not knowing octal notation might be confused that `0700` is not seven-hundred), but that can be easily relegated by using the proposed notations of `0x123, 0o123, 0b101`.

**Comment by abrander** [comment]
Octal would be extremely usefull for the `os.FileMode` type. Using base10 is a pain.

**Comment by rmunn** [comment]
If octal is included, PLEASE don't repeat C's mistake of having a leading 0 specify octal. To specify octal 755 file permissions, `0o755` should be used instead of `0755`, for consistency with hex and binary.

But I'm strongly :+1: on allowing hex and octal (via `0x` and `0o` syntax), as both are highly useful in configuration files (hex for flags, and octal for file permissions). And once you've specified `0x` for hex and `0o` for octal, there's no real reason not to include `0b` for binary, as it would feel strange not to have binary if hex and octal are available.

Allowing `0x` and `0o` (and `0b`) would not greatly complicate implementation, as most languages offer ways to parse those representations (and if they don't, writing a parser for them is not hard).

I would be :-1: on allowing hexadecimal representations of floating-point values, but there are many cases when octal or hex representation of numbers is clearer than decimal.
