### ISSUE TITLE
Question: Does there exist a TOML formatter?

### ISSUE THREAD

**Issue by alok** [toml-lang/toml#532]
I've not found one and I'd like something like the `gofmt` of TOML, if it exists.

**Comment by Ltrlg** [comment]
Your proposed implementation would lose comments which is imho a non-starter.

Programming code formatters usually do not change algorithm representation either: a language may have multiple ways to iterate over a collection, yet formatters will not change one to another (they can be coupled with linters which will emit warnings, but those have different scope). They mostly format a given syntax tree by inserting or removing blank characters. There is definitely a use for this in TOML. For example a consistent indentation style (be it “never indent”, “indent subtables”, “indent in tables” or anything one might come up with) make reading a file much easier than having mixed style, as it does for programming code.

For best practices, many formatters end with a configuration file because different peoples want different styles. One could start implementing a TOML formatter with mandatory configuration (and being open for new values), then add some default once they get user feedback.

**Comment by pradyunsg** [comment]
There's https://github.com/jumpscale7/python-pretty-toml. No clue how it is though.

**Comment by pradyunsg** [comment]
@alok has your question been answered?

**Comment by tomwhoiscontrary** [comment]
All the problems with formatting that @eksortso mentions apply to formatting code too, and yet, against all odds, code formatters exist. Personally, i just want to know whether i should put spaces inside the braces of inline tables or not.

I tried the Python prettytoml thing, but found that it preserved the whitespace in inline tables!

Oh, well, for now i will maintain artisanal hand-formatted configuration files.

**Comment by bd82** [comment]
I've created a prettier plugin for TOML.
- https://github.com/bd82/toml-tools/tree/master/packages/prettier-plugin-toml

I've also implemented my own Toml parser in JavaScript to avoid the comment losing issue described above.
- https://github.com/bd82/toml-tools/tree/master/packages/parser

It is still at an early stage and feedback would be highly appreciated 😄
