### ISSUE TITLE
Ambiguous multi-line string rules in ABNF definition

### ISSUE THREAD

**Issue by jorisvr** [toml-lang/toml#570]
First, I strongly appreciate the effort to create an ABNF definition for TOML. It is a great way to make provide a precise specification of the TOML language.

I think I found two ambigous rules in the current version of the ABNF.
1. The ABNF allows unlimited use of raw " characters inside multi-line basic strings.
2. The ABNF allows unlimited use of raw ' characters inside multi-line literal strings.

For (1), note that `ml-basic-unescaped` includes the raw character " and `ml-basic-string` may contain unlimited sequences of `ml-basic-unescaped`. As a result, the following TOML document is valid:

    a = """ multi-line basic string " "" """ """" """"" """""" still inside the string """

The following TOML document is ambiguous:

    a = """" string """ # comment or still part of the string ? """

It can be parsed either as `{"a": " string "}` or as `{"a": " string \"\"\" # comment or still part of the string ? "}`

For (2), the situation is analogous.

**Comment by eksortso** [comment]
Well, the issue was brought up again in #640, and after some insights were made, I submitted PR #648 to resolve it. It would make your first example invalid. Your second example, would be parsed as `{"a": "\" string "}` (in JSON Land).

The ABNF is still second fiddle to the README, but with #650 on the path to TOML v1.0, any push to bring the two documents together would certainly be welcome.

**Comment by pradyunsg** [comment]
I'll close this in favor of #640, since there's more discussion there.
