### ISSUE TITLE
Unclear whether raw tab is allowed inside multi-line basic string

### ISSUE THREAD

**Issue by jorisvr** [toml-lang/toml#571]
It is unclear from the specification whether raw tab characters are allowed inside multi-line basic strings.

On the one hand, the section **Multi-line basic strings** states that "_All other whitespace and newline characters remain intact._". This suggests that _all_ whitespace is allowed inside the string. And whitespace has already been defined as tabs and spaces.

On the other hand, the same section states that "_Any Unicode character may be used except those that must be escaped ... (U+0000 to U+001F, U+007F)_".

So which is it ? Allowed because whitespace, or forbidden because control character ?

The ABNF definition forbids raw tab characters inside multi-line basic strings, but the ABNF is currently not authoritative.

**Comment by pradyunsg** [comment]
Nice catch @jorisvr! :)

I think we should clarify that not "all whitespace" is allowed unescaped.

**Comment by LongTengDao** [comment]
**Basic strings** is designed to input chars which can't easy input, like control chars, use escape mark ( these marks created in computer epoch ).
**Literal strings** is designed to input the escape mark self, or content completely has no relationship with coding on computer.

So there is no difference between **basic strings** and **literal strings** about treating `Tab` -- `Tab` is a human visible charactor, like `Space` or `ABC...`. `CR` and `LF` is same to `TAB` on this, but used for file lines split, it's special only so. So the control-chars I think even should not be treated special. Because it's no reason and useless -- Unicode defined so mush control-type chars.

I think the spec should yaoqiu the editors default treat the whitespace chars in `.toml` file like:
```
# http://editorconfig.org
[*.toml]
trim_trailing_whitespace = false
```
to avoid multi string written in config file be auto changed accidentally.

`TOML` is a config format, not a transfer format, I think it could ignore many popular limit, to be as simple as possible.

**Comment by eksortso** [comment]
Even though it's fairly easy to type a tab, it seems that these whitespace characters were overlooked in the definition of multi-line basic strings, and in fact needlessly forbidden in single-line basic strings.

Let's let tabs be free in all strings. The escape code `\t` is still alright in both types of basic strings.

**Comment by pradyunsg** [comment]
> Let's let tabs be free in all strings.

Done. :)
