### ISSUE TITLE
rename toml => tml

### ISSUE THREAD

**Issue by peterwillcn** [toml-lang/toml#573]
xml
yml
so....
rename toml => tml

**Comment by eksortso** [comment]
You provide no reason why the project should be renamed. Don't be surprised if this issue is closed for no reason.

**Comment by tshepang** [comment]
I assumed they meant the file extension for some reason

**Comment by peterwillcn** [comment]
Three letters will be more neat and elegant. :-)
such as xml and yml

**Comment by TheElectronWill** [comment]
You mean such as YAML, JSON, and HOCON...?
Using three letters doesn't bring anything 🤔
You can name your files config.tml if you want though.

**Comment by eksortso** [comment]
`.tml` is smaller, but it's not as obvious as `.toml`. What happens when a user comes across a `config.tml` file for the first time?

The four-letter extension clearly owns the format's namespace online. The extension `.toml` is currently used for TOML and nothing else. `.tml` has older uses, and without the dot it'll turn up a lot of unrelated acronyms. A couple of anonymous searches on Google and DuckDuckGo verifies all this quickly. Heck, you don't even need to put "file format" after "toml" to find references to the spec fast. And an anonymous search on Github for "tml" turns up lots of interesting stuff, but nothing TOML-related. A Github search for "toml" gets you nothing but TOML-related stuff.

Less importantly, how do you pronounce "tml"? With no foreknowledge, someone would spell it out letter for letter, so it's longer to pronounce and less minimal. The [pronunciation of "toml"](https://github.com/toml-lang/toml/issues/447) isn't 100% obvious (I say _tommle_ myself, which might be the same thing) but what we've got is fairly well accepted.

That's why `.toml` will (probably) remain the official extension. Shortening it to `.tml` makes sense if you only have three-letter extensions available to work with. But that's also true of all the other modern text file formats.

**Comment by mojombo** [comment]
Thanks for taking the time to send your thoughts, however I don't think there's any problem with a 4-letter extension name. It's quite common to see these days, and it's much better for it to match the project name than to be short for shortness sake. Also, `.toml` has been in use for some time and switching now would cause a lot of confusion. Cheers!

**Comment by claweyenuk** [comment]
This hasn't been mentioned, but `.json` is a comparable format with a 4-letter extension.

I was searching for where an official extension is documented, but did not find anything. Is this already mentioned in the documentation somewhere?

**Comment by eksortso** [comment]
> I was searching for where an official extension is documented, but did not find anything. Is this already mentioned in the documentation somewhere?

@claweyenuk It's in the full specification, under its own heading titled Filename Extension. Look [here in the latest version](https://toml.io/en/v1.0.0-rc.3#filename-extension). It first appeared in [version 0.5.0](https://toml.io/en/v0.5.0#filename-extension).
