### ISSUE TITLE
Is it possible to append a previously defined value?

### ISSUE THREAD

**Issue by sahilseth** [toml-lang/toml#612]
It is possible to ask the final parser to pick up a previously defined value, and append to it?

```
[tool]
basepath = "~/apps/mytool"
binpath = "{basepath}/bin"
```

Finally, I expect the value `tool.binpath='~/apps/mytool/bin'`

I am using the `rcpptoml` parser, and not sure which is the best repo to raise this issue.
@eddelbuettel 

Thanks for nice clean config lang!

**Comment by TheElectronWill** [comment]
Unfortunately it's not possible in toml. You cannot reference another variable.

**Comment by pradyunsg** [comment]
Hi @sahilseth! Thanks for filing this issue.

I don't think this is something we'd want to have in the TOML standard since this is something that can be implemented by tools that consume TOML as additional behaviour. I understand that it might be a common use case, but the way to satisfy this would be to address it at the application level and not the TOML language level.
