### ISSUE TITLE
How about unify single-line and multi-line string syntax rules?

### ISSUE THREAD

**Issue by LongTengDao** [toml-lang/toml#623]
```
string = '
'

string_including_quotes_less_than_3 = '''
' ''
'''

string_including_quotes_less_than_7 = '''''''
' '' ''' '''' ''''' ''''''
'''''''
```

This (n*2+1: 1, 3, 7...) won't break old rules (even simplified old rules), and solved #581.
-   won't break old rules (unlike 3, 4, 5...)
-   even simplified old rules, here are only Basic String and Literal String left (unlike heredoc to bring in new syntax marks, neither <code>\`\`\`...</code> nor `<<<HERE_DOC`, which also force newline)
-   solved #581

Now I'm thinking:
1.  Is it useful enough?
2.  Which is better, "1, 3, 7, 15, 31..." or "1, 3, 7, 8, 9..."?
    -   The former maybe too long from 15;
    -   The latter maybe not obvious to count, and the rule is not unified any more which hard to remember without knowing the reason left over by history.
3.  Is it right to not only extending Multi-line String (`'''`, `'''''''`, ...), but also unify Single-line String (`'`) and Multi-line String (`'''`), to allow any type of strings including newline?

**Comment by ChristianSi** [comment]
@LongTengDao 

> Is it right to not only extending Multi-line String (''', ''''''', ...), but also unify Single-line String (') and Multi-line String ('''), to allow any type of strings including newline?

I'm against that. Strings opened and closed by just one quotation mark (whether single or double) should never be allowed to contain unescaped newlines since that would make error detection too confusing. You accidentally forget a closing quotation mark and the error is only detected much farther down in the file (or, if you're particularly unlucky, it is not detected at all and the rest of your file is just turned into a single huge string, much to your dismay).

If course, such things can happen with triple-quoted strings too, but they are much rarer and people will tend to be more careful when using them.

**Comment by pradyunsg** [comment]
What's the use case of this? I dislike this for reasons I'll state when I reach a computer f

**Comment by pradyunsg** [comment]
Pressed the wrong button at the wrong time. 🤷🏻‍♂️

Edits made for those following via email.

**Comment by pradyunsg** [comment]
I'm still on phone. "fun"

As @ChristianSi pointed out, there's almost no past precedent for doing single quoted strings that can span multiple lines. That is off the table and not going to happen in TOML. 

Regarding an arbitrary (odd) number of quotes, that's basically a variation of #581 and I don't want to have a conversation about very similar syntax + objectives in 2 places.

I'm going to close this issue (intentionally this time 🙃) in favor of #581. As always, thanks @LongTengDao and @ChristianSi for your comments here!
