### ISSUE TITLE
reference implementation 

### ISSUE THREAD

**Issue by catastrop** [toml-lang/toml#633]
Is there is a reference/official implementation of TOML?

if not, why it doesn't?

**Comment by pradyunsg** [comment]
> Is there is a reference/official implementation of TOML?

No.

> if not, why it doesn't?

This sort of forces the specification to be unambiguous and clear (since there's no other reference to look at); I guess the hope is parser implementers will flag any cases that they view as being ambiguous, so that we clarify them at the specification level. FWIW, I'm exploring creating a standard test suite, so that implementations can verify their compliance to the standard (see #25). :)

TBH, blessing certain implementations as "official" doesn't get us anything.

**Comment by pradyunsg** [comment]
Thanks for asking @catastrop! :)

**Comment by catastrop** [comment]
this is good. thank you.
