### ISSUE TITLE
jq command line tool for manipulating toml files?

### ISSUE THREAD

**Issue by mcandre** [toml-lang/toml#645]
Hi, I am curious if there could be a CLI tool similar to jq or yq, for conveniently querying and transforming TOML files?

**Comment by mmakaay** [comment]
It's a structured data format, so looking at what jq does, it seems to me that similar things could be done for TOML. All it needs is somebody to be inspired to write the tool.

Could you explain what the practical use cases for such tool would be for you? For jq I can imagine a few use cases easily, JSON being a popular data transport format. To me TOML is a configuration format, making such tool less of a natural fit.

One use case that pops to mind for me would be the use of `tq` (let's call it that ;-) ) from within for example bash scripts, making it possible to use configuration data from TOML files easily from within those scripts. Of course the same goes for running commands from a shell, and for which you want to extract some configuration data from a TOML file.
But for these use cases (which I do find interesting myself), wouldn't need much more than a basic query tool, to fetch values and lists from a TOML file. It would not need transformation capabilities to filter a TOML file and export a transformed / filtered new TOML file.

**Comment by pradyunsg** [comment]
There could be -- there isn't one yet AFAIK.

Folks are more than welcome to make one!

**Comment by FranklinYu** [comment]
I found this: https://github.com/jamesmunns/tomlq

Hope it helps! Or maybe you can also contribute.

**Comment by diraol** [comment]
Just for the record, a tool like that is usefull (for me) to be able to automate tests against toml files.

Or either to automate chances in toml files in a more robust way than sedops would do. :)

**Comment by TomWright** [comment]
Another useful tool is this: https://github.com/TomWright/dasel

It supports JSON, YAML and TOML.

**Comment by neilmayhew** [comment]
Didn't know that there are actually two `yq`s, one in Python and one in Go.

* Python: https://kislyuk.github.io/yq/
* Go: https://mikefarah.gitbook.io/yq/

**Comment by Alex-ley-scrub** [comment]
https://github.com/4rbor/tq

**Comment by jthetzel** [comment]
For python, there is now toml-cli ( https://github.com/mrijken/toml-cli ).

I found it helpful for parinsg pyproject.toml files from the terminal.
```
uv add toml-cli
uv run toml get --toml-path=pyproject.toml project.version
```

**Comment by azolfagharj** [comment]
Hey! If you're working with TOML files and wish there was a jq for TOML, check out tmq - a fast, script-friendly CLI tool for querying, modifying, and converting TOML files! 
🚀 GitHub
https://github.com/azolfagharj/tmq

**Comment by neilmayhew** [comment]
It's great to see all these alternative tools being made available.

However, for me, the Python `yq` has a big advantage for TOML: it uses `jq` for the heavy lifting so the query language for both TOML (and YAML) is exactly the same as what I'm already used to using with `jq`. It's important to me that I don't have to learn yet another mini-language.

Also, I already have `yq` installed, since I have to query YAML files from time to time, so I'm glad not to have to install an additional tool for TOML.

Note that the query language for the Go `yq` is NOT the same as the one for `jq`, which is widely enough used to have become a _de facto_ standard. For this reason I always use the Python version.
