### ISSUE TITLE
Escaped quote rules

### ISSUE THREAD

**Issue by lschumm** [toml-lang/toml#657]
I've been working on implementing a TOML parser, and while reading through the section about string parsing, I came across the following list of valid escaped characters:

```
\b         - backspace       (U+0008)
\t         - tab             (U+0009)
\n         - linefeed        (U+000A)
\f         - form feed       (U+000C)
\r         - carriage return (U+000D)
\"         - quote           (U+0022)
\\         - backslash       (U+005C)
\uXXXX     - unicode         (U+XXXX)
\UXXXXXXXX - unicode         (U+XXXXXXXX)
```

TOML does appear to support single-quotes as string delimeters; would `\'` also be part of this set?

I was also wondering whether this depended on the delimiter of the string which the escaped characters appeared. For example, in a string using double quotes, would an escaped single quote be valid? Likewise, in a string using single quotes, would an escaped double quote be valid?

**Comment by eksortso** [comment]
For all practical purposes, `\'` is not necessary. That's why it's not valid.

The delimiters do matter significantly. Double quotes delimit _basic strings,_ in which apostrophes don't need to be escaped. (Of course, double quotes inside need to be escaped, as do backslashes.) So `"'"` is an apostrophe, and `"\'"` is _invalid_

Single quotes delimit _literal strings,_ in which there are no escapes whatsoever. Long story short, what you type is what you get. When your values are `'\''` and `'\"'`, TOML literally gives back out `\'` and `\"`.

**Comment by lschumm** [comment]
@eksortso thanks for the clarification!

**Comment by eksortso** [comment]
Whoops. I made one mistake...

You can't put an apostrophe in a literal string, because apostrophes delimit literal strings. So `'\'` will get you `\`, and `'\''` will get you an error because isn't a valid string.

There are multiline strings, both basic and literal, But the same logic applies to them, as far as escapes and apostrophes go.

**Comment by lschumm** [comment]
oh haha, didn't notice that. good luck with the BNF work!
