### ISSUE TITLE
Cleanup sentence on out-of-order definitions

### ISSUE THREAD

**Issue by ChristianSi** [toml-lang/toml#659]
The spec contains the following sentence, added per #646:

> Similarly, defining tables out-of-order is discouraged as well.

This sentence should be changed to:

> Defining tables out-of-order is discouraged.

Rationale: The preceding sentence is

> Like keys, you cannot define any table more than once. Doing so is invalid.

hence "similarly" and "as well" don't fit the context. In #646, the implied context was

> Defining dotted keys out-of-order is discouraged.

but that sentence occurs much earlier in the complete spec, hence that context got lost upon merging.

**Comment by pradyunsg** [comment]
I'm cool with this.

**Comment by AndrewSav** [comment]
`Defining dotted keys out-of-order is discouraged` is confusing. For a person who is not privy to all the issue threads, it is not clear at all what does this mean. Does it mean that if you do that you risk being incompatible in future? Or does it mean that authors of the TOML do not like it because it's their personal taste?

I think that this phrase in it's current form is not a good fit for the spec. Either remove it completely or elaborate what it means, as for the first tine reader it's not clear at all.

**Comment by ChristianSi** [comment]
@AndrewSav: The spec "discourages" things at several occasions:

* A bare key must be non-empty, but an empty quoted key is allowed (though discouraged).
* Defining dotted keys out-of-order is discouraged.
* Similarly, defining tables out-of-order is discouraged as well.
* No newlines are allowed between the curly braces unless they are valid within a value. Even so, it is strongly discouraged to break an inline table onto multiples lines.

I'd say that "discouraged" is meant as a synonym for "considered bad style". I'd suppose that the dotted-key case is the only one which conceivably might be forbidden in TOML 2.0 -- certainly not earlier than that.
