### ISSUE TITLE
How to Cite

### ISSUE THREAD

**Issue by alan-isaac** [toml-lang/toml#685]
Please add a "how to cite" section to the Wiki, providing an unambiguous "official" way to cite a TOML specification version. Example (for illustration only; not a proposal): 

@manual{TOML-2018,
  title={TOML Specification version 0.5},
  author={Preston-Werner, Tom},
  url={https://github.com/toml-lang/toml/blob/v0.5.0/README.md},
  year={2018},
  month={July}
}

**Comment by pradyunsg** [comment]
I guess? I'm not sure to be honest.

**Comment by pradyunsg** [comment]
This is still an open question -- I welcome anyone who has experience with academic citations to help us figure this out.

**Comment by ChristianSi** [comment]
I would not bother with the BibTeX stuff, which is only used by some researchers, and just show an example citation formatted in a more or less typical way. Say, for the last RC:

> If you want to cite this version of the specification, you may do so as follows (adopt to your citation style as needed):
>
> > Preston-Werner, Tom, Pradyun Gedam, et al. *TOML Specification, Version 1.0.0-rc.1.* April 2020. https://toml.io/en/v1.0.0-rc.1.

To be adapted for other released versions in the obvious way. It's probably a bad idea to write this in the spec itself, since then it would need to be manually adapted for each new version, which would be very error-prone. However, now we have a website (yeah!), it should be possible to add a "How to cite this" button near the start or end of the spec, which then opens a suitable autogenerated entry when clicked.

**Comment by alan-isaac** [comment]
Christian's [proposal](https://github.com/toml-lang/toml/issues/685#issuecomment-648952821) would mostly work fine for me. However, for any version there should be a canonical author list. (It is ok is the author is a group name, if there is one with a clear meaning.)

**Comment by ChristianSi** [comment]
@alan-isaac Hmm, what kind of "group name" do you have in mind?

**Comment by alan-isaac** [comment]
> what kind of "group name" do you have in mind?

All that is important is that there be an unambiguous attribution of authorship. So, a complete listing of author names is perfect.  But so is, e.g. TOML Working Group, as long as this is an actual entity that can be considered to hold the original copyright of the document.  The author is ordinarily the original copyright holder. Being a contributor is [not the same](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html) as being an author.  

My only point really was that "et al." cannot be in the canonical citation. That abbreviation  is chosen for a citation at the *publication* end, if the author list in the citation is considered to be too lengthy.

**Comment by pradyunsg** [comment]
Would the phrase "TOML Core Maintainers" work for this?

**Comment by ChristianSi** [comment]
In my viewpoint, Tom and Pradyun must be mentioned personally to recognize their contributions.

Would 

> Preston-Werner, Tom, Pradyun Gedam, and the other TOML Core Maintainers

be better than

> Preston-Werner, Tom, Pradyun Gedam, et al.

? I'm not so sure...

**Comment by alan-isaac** [comment]
I suspect the Core Maintainers are [contributors rather than authors](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html), so they should receive an acknowledgement note in the document rather than authorship credit.  However, I would personally find *Preston-Werner, Tom, Pradyun Gedam, and TOML Core Maintainers* to work (it's fine that other authors are also in the group).  Warning: I do not claim even remotely to be a citation style expert.

**Comment by ChristianSi** [comment]
@alan-isaac: I'm not convinced. For one thing, that would sound as if Tom and Pradyun were *not* TOML Core Maintainers; moreover, the reference is somewhat pointless, since nobody know who the "TOML Core Maintainers" are supposed to be anyway.

Also, the "[By] Tom Preston-Werner, Pradyun Gedam, et al."  is not something I made up, it's already on top of the current version of the spec as well as TOML v1.0.0-rc.1. There is no *law* against a group of authors et al.-ing themselves, and in my viewpoint it's the right thing do so, because it recognizes the significance of everyone who contributed text, examples, or ideas without being personally named (and personally naming all of them would be impossible). Maybe that's not how you do it when you submit a paper to a peer-reviewed journal, but then, the spec is not a scientific paper. Different rules apply here.

So, my personal plea would be to leave the "et al." in place. Anyone who wants to cite the spec will be able to deal with it.

(In earlier versions up to v0.5.0, on the other hand, the byline read just "By Tom Preston-Werner". Ideally the How to Cite button will reflect this.)

**Comment by alan-isaac** [comment]
> There is no _law_ against a group of authors et al.-ing themselves

Of course; you can just make stuff up if you want to. At that point, however, it is probably best to drop the Latinism and just say "and others".  Of course, at *that* point, somehow indicating the nature of those "others" seems called for, especially if they are really authors and not just contributors (again, [this link](http://www.icmje.org/recommendations/browse/roles-and-responsibilities/defining-the-role-of-authors-and-contributors.html)).  But whatever.

**Comment by pradyunsg** [comment]
If the distinction between authors/contributors is really binding, I'm personally OK with the following (although only barely):

> Tom Preston-Werner, Pradyun Gedam. TOML Specification 1.0.0-rc.1. April 2020. URL: https://toml.io/en/v1.0.0-rc.1/

---

I'm going to leave this open, but I don't think this is a blocker or even on the roadmap for any future TOML releases.

**Comment by pradyunsg** [comment]
And... given the lack of responses, closing this.

**Comment by Anselmoo** [comment]
> I would not bother with the BibTeX stuff, which is only used by some researchers, and just show an example citation formatted in a more or less typical way. Say, for the last RC:
> 
> > If you want to cite this version of the specification, you may do so as follows (adopt to your citation style as needed):
> > > Preston-Werner, Tom, Pradyun Gedam, et al. _TOML Specification, Version 1.0.0-rc.1._ April 2020. https://toml.io/en/v1.0.0-rc.1.
> 
> To be adapted for other released versions in the obvious way. It's probably a bad idea to write this in the spec itself, since then it would need to be manually adapted for each new version, which would be very error-prone. However, now we have a website (yeah!), it should be possible to add a "How to cite this" button near the start or end of the spec, which then opens a suitable autogenerated entry when clicked.

1. Where can you find the date of publishing, actually? 
2. Do you get it just from the release? 
3. Is the published release similar to the referenced webpage in terms of published date?

Thx for feedback
