### ISSUE TITLE
why multiline basic string can ends with " inside now, while multiline literal string still can't ends with '?

### ISSUE THREAD

**Issue by LongTengDao** [toml-lang/toml#725]
I saw this is valid in v1.0.0-rc.1 now, which is different from v0.5.0:

```toml
str = """she said: "...""""
```

But what's the rule, how should I write the parser, and remember it while writing toml config file? Is this valid too?

```toml
str = """..."""""
```

even:

```toml
str = """...""""""
```

?

If they are all valid, then why this is invalid?

```toml
str = '''15: ''''''''''''''''''
```

I saw "You can write 1 or 2 single quotes anywhere within a multi-line literal string, but sequences of three or more single quotes are not permitted." in the spec.

Does this mean that, both multiline basic/literal can include ending quote marks, only if they are shorter than three? If so, I don't think current doc said it clear, neither explains nor examples.

PR is easy, but need to make sure at first.

**Comment by marzer** [comment]
It means that the first time the sequence `'''` is seen inside a multi-line literal string it terminates the string, so for practical purposes you can't have three of them consecutively unless you intend to end the string.

You're right to point out that it's not the same as regular ML strings, though. I have no idea why a distinction is made between the two on this point. @pradyunsg, any input here?

**Comment by eksortso** [comment]
Since I wrote the original PR, I'll do my best to explain. If we do need better examples than the ones in the README, then go ahead and post them.

Sorry @marzer, but triple quotes don't immediately end a string if there are quotes at the end of the string. I know that was the original plan. But it's slightly different now.

Sequences of one or two `'`s are allowed within multiline literal strings. What that means, by extension, is that a single set `'''` is not necessarily the end of the string, because 1 or 2 quotes are allowed at the end. So a series of 3, 4, or 5 quotes terminates a MLL string that ends with 0, 1, or 2 quotes, respectively. And actually, in MLBs, you could even have 6 in a row, if the first one is escaped:
```toml
this-in-quotes-plus-two-more = """"THIS\""""""
#                                 ^^^^^-^^^
```

@LongTengDao, let me point out the strings in your examples. I'll keep highlighting turned off, because as of now, GitHub's TOML highlighting is out of date.

```
# Example 1
str = """she said: "...""""
#        ^^^^^^^^^^^^^^^
# Four quote marks at the end;
# the first one is part of the string,
# and the last three terminate the string.

# Example 2 is VALID.
str = """..."""""
#        ^^^^^
Same rule: 5 quotes, 2 on the inside.

# Example 3 is NOT VALID.
#str = """...""""""
##        ^^^^^!
# 6 single quotes in a row are not allowed.
# You can have 1 or 2 quotes in a row on the inside, but not 3.

# So Example 4 is also NOT VALID.
#str = '''15: ''''''''''''''''''
#         ^^^^^!!!!!!!!!!!!!!!!!
```

The original discussion is here: #640. This is an example of formatting that is intended to be obvious to users, even if it isn't immediately obvious or necessarily convenient for parser developers.

**Comment by marzer** [comment]
@eksortso Yah, I know the way the string ending thing works (i.e. that `"""` doesn't end the string if there's more `"` after it), but I was referring to the documentation of the ML literal strings, which I went and re-read and it seemed ambiguous, though I guess it is the same.

**Comment by LongTengDao** [comment]
@eksortso Do you mean this?

```
quot0=""" """ # valid
quot1=""" """" # valid
quot2=""" """"" # valid
quot3=""" """""" # invalid
apos0=''' ''' # valid
apos1=''' '''' # valid
apos2=''' ''''' # valid
apos3=''' '''''' # invalid
```

**Comment by LongTengDao** [comment]
@marzer @eksortso Thank you! I read the history issue and PR I missed, and clear now.

**Comment by abelbraaksma** [comment]
@eksorto Just to make sure I understand this properly. Essentially, after you strip a verbatim string from three single it double quotes at the beginning and end, the part that's left can have single or double quotes resp. but not more than two consecutively.

Taking @LongTengDao's example a little further gives:

```
quot0=""" """ # valid
quot1=""" """" # valid
quot2=""" """"" # valid
quot3=""" """""" # invalid
apos0=''' ''' # valid
apos1=''' '''' # valid
apos2=''' ''''' # valid
apos3=''' '''''' # invalid

quot4="""""" # valid
quot5="""" """ # valid
quot6=""""" """ # valid
quot7="""""" """ # invalid
apos4='''''' # valid
apos5='''' ''' # valid
apos6=''''' ''' # valid
apos7='''''' ''' # invalid

quot8="""""\"""""" # valid (5 at start, 6 at end) 
quot9="""""\"""\"""""" # valid (3 in the middle 5 at start, 6 at end) 
```

A little extreme may be, but handy to test parsers.

**Comment by eksortso** [comment]
@abelbraaksma @LongTengDao Those examples would serve as really good tests, I think!

**Comment by marzer** [comment]
Thanks @abelbraaksma, you just [helped me fix some bugs](https://github.com/marzer/tomlplusplus/blob/cd9b3d2198b496f40a66aa626f471530650ec72a/tests/parsing_strings.cpp#L196)! :D
