### ISSUE TITLE
TOML v1.0.0-rc.3?

### ISSUE THREAD

**Issue by ChristianSi** [toml-lang/toml#773]
Maybe now would be a good time to release RC.3? RC.2 was published nearly three months ago and only one issue (PR #767) had to be fixed since then.

It therefore seems we're getting really close to 1.0 Final! If we release RC.3 now and nothing important comes up, we could finally publish Final six weeks from now or so, thus managing a 2020 birthday.

#769 seem to be the only open issue that could possibly need addressing before a new RC is published – but it's just a "clarification" which (if not delayed until after 1.0) likely can be handled outside the spec proper, say by writing a FAQ entry.

**Comment by eksortso** [comment]
I think I will pick up [#769](), and attempt to provide the necessary clarification over the next few days. Mostly I'll focus on the distinction between creating and defining tables, but I also wish to define what the document sections are in regards to the table headers, because doing so would help to describe the scope of dotted keys' table definitions.

**Comment by pradyunsg** [comment]
I think #769 doesn't really _need_ to be addressed directly before 1.0 -- it'd be nice but isn't _required_.

I'll cut 1.0.0-rc.3 once I add a few lines to automate the last little bits for the website.

**Comment by pradyunsg** [comment]
Done: https://toml.io/en/v1.0.0-rc.3
