### ISSUE TITLE
String lists

### ISSUE THREAD

**Issue by yobson** [toml-lang/toml#783]
Hello! I have a syntax proposal for TOML

### Motivations
Sometimes you need to add scripts to configuration files. If you take a look at most CI/CD git software,
you will notice that YAML is used. That is because of the following syntax:
```YAML
script:
    - echo -n hello
    - echo " world"
    - anImportantShellCommand
```
Which is simply syntactic sugar for:
```YAML
script: ["echo -n hello", "echo \" world\"", "anImportantShellCommand"]
```

I think TOML needs to steal this idea because it is fantastic!

### Syntax proposal
I think in order to ensure the best implementation of this feature, strings are terminated by
a newline *only*. This means that no escaping is needed on each line. This ensures really simple
and power usage when scripts are placed in toml files. I use CI/CD as an example. Luckily, I think
we can actually lift the YAML syntax verbatum. The colon instead of an equals could be a nive easy way
for parsers to know a list if comming. Alternativly we could keep the equals signs as I have done below.

```
[[stage]]
name = "build"
can_fail = "false"
script =
    - ./autoreconf
    - ./configure --prefix="/tmp/CI\ CD"
    - make -j
artifacts =
    - build/release
    - build/debug
```

**Comment by marzer** [comment]
> If you take a look at most CI/CD git software, you will notice that YAML is used. That is because of the following syntax: [snip].

Hard disagree. [YAML is error-prone garbage](https://noyaml.com/) and the further any YAML features stay from TOML, the better.

The TOML equivalent is already clean and unambiguous:
```toml
script = [
	'echo -n hello',
	'echo " world"',
	'anImportantShellCommand'
]
```

**Comment by pradyunsg** [comment]
@marzer I agree that YAML has a *lot* of edge cases which do result in a lot of surprising behaviors and errors. However, calling it "garbage" is a bit too far, especially on this issue tracker where I'd prefer that folks don't paint design decisions made in other markup languages in a negative light.

**Comment by pradyunsg** [comment]
Thanks for filing this @yobson.

This is an intentional design choice, to keep TOML unambigous at the cost of being slightly more verbose. The current syntax is consistent, unambigous and does not need special casing "what is a string". As @marzer's example shows, TOML's current approach here is good enough.

There is a (significant) cost to providing multiple ways to do things and I don't think the benefits from adding this are worth it. The fact that we'd need to introduce string escaping rules to make the proposed syntax work well is a deal breaker. If we avoid that by requiring quoting, it's easy-enough to add a `,` after instead of `-` before -- which brings us to status quo.

I don't think the proposed syntax (or anything like it) should be added to TOML.

**Comment by yobson** [comment]
Thanks anyway!
