### ISSUE TITLE
Suggestion: allow use of variables

### ISSUE THREAD

**Issue by gustavofujita** [toml-lang/toml#829]
Something like string interpolation:

key = "value"
another = "The value is %value%"

ip = "10.0.0.1"
server_ip = %ip%
remote_ip = %ip%

**Comment by pradyunsg** [comment]
I don't think this complexity belongs in TOML -- rather it is better suited for a templating engine or as an application-specific, if it is deemed necessary by the tool authors.

This has been previously brought up in https://github.com/toml-lang/toml/issues/686, https://github.com/toml-lang/toml/issues/528, https://github.com/toml-lang/toml/issues/606 and more. Please read those.

**Comment by KOLANICH** [comment]
It is a feature of YAML.

**Comment by KOLANICH** [comment]
(partially, no templating, but pointers reuse are supported)

**Comment by marzer** [comment]
> It is a feature of YAML.

This alone is not really an argument for or against it being a part of TOML (personally I'm very strongly against bringing TOML closer to YAML for many, _many_ reasons); different languages can have different scopes, and that's OK.

**Comment by KOLANICH** [comment]
I completely aggree. I personally am aginst interpolation in package metadata formats, because package metadata are the thing that must be automatically scannable and indexable. But allowing sharing vars opens it to [billion laughs attack](https://en.wikipedia.org/wiki/Billion_laughs_attack).

**Comment by Moosems** [comment]
I believe that variables in a data-oriented language can still be simplistic and it removes a lot of boilerplate code and repetition.

**Comment by eksortso** [comment]
This issue was closed months ago. @Moosems If you have an idea for a very simple (and very safe) way to implement variables and string interpolation in TOML without making the standard any less obvious upon first inspection, then go ahead and open a brand new issue. But do read through #686, #528, and #606 first, at least.

I'm personally not against the idea, but if there's any more than one pass of string interpolation in your proposal, consider me out.
