### ISSUE TITLE
Suggestion: allow use of separated files

### ISSUE THREAD

**Issue by gustavofujita** [toml-lang/toml#830]
Something like this:

```
#include "general.toml" # include the content of file general.toml
#include "moduleA.toml"
```

**Comment by pradyunsg** [comment]
Same rationale as #829 -- this isn't something for TOML; but for a templating engine on top of it or as application-specific logic, by the tool that's consuming the TOML file(s).

**Comment by jibbers42** [comment]
@pradyunsg There are a number of issues that are closed due to introducing more complexity than you would like. Declining these more complex features is, of course, a valid choice and simplicity seems to be a/the core principle for this project. That said, it would be great to reconsider this again in light of the common use case where project config choices may not be optimal...

Anchor (https://github.com/project-serum/anchor) uses TOML for some of its config. Sharing the config is nice for some settings, but not for others. In the example below, it's great to share the `my_program` id, but it would be nice to `#include provider.toml` and .gitignore that file. A dev may also want to include some local scripts without pushing them to git.

I'm imagine this is a very common situation. I'm sure Anchor could do things differently, but includes allow me to solve this without convincing every project with similar issues to do things some other way.

```
[features]
seeds = false
[programs.localnet]
my_program = "EaPB7vygqXRxHa9PuE5LRtKaHF6SXkpyu8QjToMR8BFq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "<path to my home folder>/.config/solana/<my file>.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
```
