### ISSUE TITLE
Add the concept of tokens in TOML spec or somewhere else

### ISSUE THREAD

**Issue by LongTengDao** [toml-lang/toml#858]
As a TOML implementer, I implemented `TOML.parse` and `TOML.stringify`, but when I want to implement `TOML.tokenize` (for highlight), I found it hard to decide what is a token uint without spec specifying.

For example,

- `[[` is 1 or 2 `[` tokens?
- `-nan` is 1 or 2 tokens (`-` and `nan`)?
- `0000-00-00 00:00:00` is 1 or 2 or 11 tokens?
- basic string is a whole token, or each side quotation marks and each escaping even "line ending backslash" in that is a token?
- when found an invalid `xxx` literal as value, it's a single bad token (which may cause compatibility problem in the future), or tokenizer should stop tokenizing (which not loose and friendly for user inputing)?
- `#xxx` is 1 or 2 tokens? or comment is like whitespace, that's not a token?

**Comment by arp242** [comment]
I think this is really an implementation detail that the TOML spec doesn't really need to say anything about.

As for syntax highlighting: just do whatever you think makes sense? It's a matter of some personal taste.

**Comment by LongTengDao** [comment]
> I think this is really an implementation detail that the TOML spec doesn't really need to say anything about.
> 
> As for syntax highlighting: just do whatever you think makes sense? It's a matter of some personal taste.

HTML, CSS, JS, JSON all have token concept in spec, I think It is of great practical help to ecology establishment

**Comment by marzer** [comment]
> I think this is really an implementation detail that the TOML spec doesn't really need to say anything about.

I agree with this. I do not think having a strict specification in the spec of what comprises a 'token' would have helped my implementation at all, and I'd likely have just ignored it anyway.

**Comment by ChristianSi** [comment]
I agree with various comments that a Token concept doesn't belong into and it not needed for the spec. Various implementations may reasonably handle this in different ways, or not use a Token concept at all. In any case it's an implementation detail, irrelevant for the normal user.

As for the original question, I think the question "Can it be interrupted by whitespace?" can provide useful guidelines. `[[` cannot be interrupted by whitespace, hence it makes sense to consider it a single token. On the other hand, `-nan` can also be written as `- nan`, hence it's two tokens. Etc.

**Comment by LongTengDao** [comment]
(`-nan` can not be written as `- nan`)

**Comment by abelbraaksma** [comment]
> HTML, CSS, JS, JSON all have token concept in spec

Interesting that you mention these. The only one of these with a somewhat useful token definition, albeit informally, is JSON. In CSS, the tokens are defined recursively, for instance `DIMENSION` exists of `NUM` and `IDENT`, which themselves are also tokens. This allows implementers to choose whether to color these parts differently or not.

HTML explains it pretty well: "Implementations must act as if they used the following state machine to tokenize HTML". The key here is "as if". For instance, look at [tokenizing a character ref](https://dev.w3.org/html5/spec-LC/tokenization.html#consume-a-character-reference). This is a whole process, but any editor will likely color the entire character reference in one color.

In TOML, we use [ABNF](https://www.rfc-editor.org/rfc/rfc5234#page-4), which uses _productions_ (aka _rules_) and _terminals_. Colloquially these are often called _tokens_. This is very similar to other BNF-style languages. As [this discussion shows](https://stackoverflow.com/questions/66737864/how-to-tokenize-input-based-on-a-set-of-abnf-grammar-rules), see comments, it's really up to the implementer, as others have already mentioned here.

Since ABNF specifically does _not_ talk about tokens, I think it would be foolish to try to define them. Ultimately, every production rule ends recursively in one or more terminals, but in practice, tokenizers will choose higher-level productions than just mere characters for their tokenization. I.e., I would choose to color a whole string, and not the opening/closing quote and individual characters separately.

**Comment by pradyunsg** [comment]
Picking what productions should be handled by an implementation's tokenizer should live at... is a concern for the parser authors. There are non-tokenising parsers out in the wild as well and I don't think the spec needs to cover this implementation concern in that level of detail.

I'm more than happy to trust the parser authors to figure out the right parsing models and to make the design choices on what tokens should look like, coming out of the tokenizer.
