### ISSUE TITLE
Toml Version Declaration

### ISSUE THREAD

**Issue by jeff-hykin** [toml-lang/toml#860]
I haven't seen anywhere in the spec, or in the issues, discussing how to specify the toml version (which I find very surpising). 
In the case that there really is no previous dicussion on this, I'd like to request that there be some way to tell the parser the minium or exact version of toml the document is supposed to use.

For example, with most parsers currenly being at the v0.4 spec, it would be nice to tell them that a document follows the v1.0 spec and they shouldn't be throwing errors about `key.subkey = 10`. 

I do not have a propsal on the exact syntax, as I think the current contributor would do a better job of choosing than myself. An example implmentation would be the (not particularly elegant) implmentation that YAML chose with declarations using a percent sign: `%YAML 1.1` or `%YAML 1.2`.

**Comment by marzer** [comment]
> I haven't seen anywhere in the spec, or in the issues,

- #522
- #542 (closed without comment, I guess after the additional discussion in 522)
- #661
- #816 (tangentially related)

>  with most parsers currenly being at the v0.4 spec,

How do you figure that? A cursory look at the list of parsers on [the wiki](https://github.com/toml-lang/toml/wiki) suggests that "most" being 0.4 is generous at best. Quite a few still, sure, but "most" suggests an outright majority and that's not nearly the case. The actual counts are thus (at the time of writing):
- v1.0: 28
- various v1.0 RCs: 7
- v0.5: 19
- v0.4: 29
- v0.3 and earlier: I didn't bother counting since they're pretty much all abandonware at this point

(also FWIW a new v1.0 implementation is still popping up [every few weeks or so](https://github.com/toml-lang/toml/wiki/Home/_history))

>  it would be nice to tell them that a document follows the v1.0 spec and they shouldn't be throwing errors about `...`

So, given this feature, a v0.4 parser should have awareness that v1.0 exists, and know what special casing to apply when given a v1.0 document? If the developer of a v0.4 parser is still maintaining it to add such a feature their time would be better spent implementing 1.0 support, IMO.

**Comment by jeff-hykin** [comment]
Thanks for the issue link, I guess I should've searched for pragma instead of declaration.

That link to the wiki is also much appreciated, I will be making great use of that. My numbers were just from skimming package managers, like npm and pypi, and the top 5 or so advertised being "up to v0.4".
