### ISSUE TITLE
Is any benchmarking info available comparing different implementations?

### ISSUE THREAD

**Issue by pkbehera** [toml-lang/toml#869]
The [Wiki](https://github.com/toml-lang/toml/wiki) lists many implementations of the TOML standard. It would be nice if some benchmarking data was made available too, to help user chose which implementation they want to use.

**Comment by pradyunsg** [comment]
No, this is not available in the Wiki at this time. If someone wants to create this independently, they're welcome to do the work! :)

**Comment by arp242** [comment]
Some work here: https://github.com/arp242/toml-test-matrix / https://arp242.github.io/toml-test-matrix/

The biggest blocker is that I don't know all programming languages in the world, and that it's hard for me too add too many more (will add Ruby and JS later).

e.g. I looked at Julia this morning, and, ehh, it was difficult – not just the language itself, also that the Julia interpreter is too slow to start and running the tests take forever because of that, and I can't figure out how to compile things (if that's possible at all).
