### ISSUE TITLE
Strings as "UTF 8 byte sequences"

### ISSUE THREAD

**Issue by paulehoffman** [toml-lang/toml#890]
The spec for floats says "Floats should be implemented as IEEE 754 binary64 values." This seems reasonable to me. However, when I proposed that strings should be implemented as UTF8-encoded text (because the TOML file itself is in UTF8), I get pushback. 

For consistency, either the text about floats should be removed, or the spec should be able to say what TOML interpreters output for the various formats. (I have no strong opinion in either direction.)

**Comment by pradyunsg** [comment]
> However, when I proposed that strings should be implemented as UTF8-encoded text (because the TOML file itself is in UTF8), I get pushback.

The language you've proposed is:

> Strings should be implemented as UTF-8 byte sequences.

UTF-8 byte sequences for a language like Python would imply that implementations should use `bytes` (an immutable array of bytes) vs `str` (the string type). Similarly, for Rust, that would imply being `[u8; ...]` instead of `String`.

That's why I think it is not the appropriate phrasing.

**Comment by ChristianSi** [comment]
I believe the "consistency" argument is mistaken. For most data types, there is either just one typical way in which they are represented in a specific programming language, or if there are several ones, if doesn't matter much which one is used.

Take boolean: Most programming languages have some boolean data type, and TOML implementations in these languages will certainly use that type to represent TOML's booleans. Some languages (such as Perl) don't have a specific boolean type, and so implementations will represent TOML's booleans in a way that makes sense in their language, maybe as 1 and 0. We don't this discuss this, and why should we? Implementers are not stupid, they will know what to do.

With strings it's quite similar. The important thing is that TOML's strings are Unicode, so implementers must choose Unicode string type – they must not, say, use an 8-bit string type, discarding all characters that don't fit. So far it should be obvious. And nearly every language already has some type for that. Maybe it internally treats each character as a number, effectively implementing something like UTF-32; Java internally uses some variant of UTF-16; other languages internally implement Unicode strings as UTF-8 byte sequences. So does it matter which of these types is used? Not at all – Unicode is Unicode, so as long the used string type is able to handle that, it's fine.

With floats the situation is somewhat different because there are different ways of implementing real numbers, and they lead to subtle different results. Numbers represented as sequences of decimal digits will often be minimally different from those represented in binary [floating-point arithmetic](https://en.wikipedia.org/wiki/Floating-point_arithmetic) (FP), to due rounding issues. Without further guidelines, TOML implementers might be inclined to use the "decimal" data type of their language, if it has one, since floats are represented as sequences of decimal digits in the file. But this might lead to problems when mixing them with the FP numbers that are much more commonly used in programming. Another issue is the precision. The name "Float" might suggest at first sight that the C type "float" with (normally) 32 bits is sufficient, but TOML actually expects the 64-bit "double" type. But since this is not obvious, the spec must explain it, and it does.
