### ISSUE TITLE
nesting proposal : {} block

### ISSUE THREAD

**Issue by lizelive** [toml-lang/toml#900]
```
[creature.crow] {
    color = "black"
    [name]
        singular = "crow"
        plural = "crows"
        adjective = "crow"
}
```
i prefer https://github.com/toml-lang/toml/issues/898 because it feels more consistent

**Comment by pradyunsg** [comment]
Hi! Please see https://github.com/toml-lang/toml/issues/781 which discusses the broader topic here.

**Comment by eksortso** [comment]
@lizelive I would like to give your suggestions some serious thought, but the examples are confusing because they assume that their meaning is immediately evident, when it is not.

Before we take these up on #781, could I offer a suggestion? If you are making a proposal for new TOML syntax, could you please also include how each of your examples would be written in current TOML formats, without the excess indentation?
