### ISSUE TITLE
Table section editing inline table in inline array

### ISSUE THREAD

**Issue by brandonchinn178** [toml-lang/toml#908]
The spec says:

> Any reference to an array of tables points to the most recently defined table element of the array.

which means that this is currently valid (verified at http://toml-online-parser.ovonick.com/):

```toml
a = [{ b = 1 }]
[a.c]
foo = 1
```
```json
{
    "a": [
        {
            "b": {"type" : "integer", "value" : "1"},
            "c": {
                "foo": {"type" : "integer", "value" : "1"}
            }
        }
    ]
}
```

which seems a bit inconsistent since extending inline tables in general is invalid:
```toml
a = { b = 1 }
[a.c]
foo = 1
```
Is this intentional?

**Comment by marzer** [comment]
> array of tables

"Array-of-tables" in this context does not mean any normal array containing inline tables (as in your example), but a specific language construct for representing table elements of arrays using the `[[array.of.tables]]` syntax. To re-write your example using what the spec document actually means, it would be this:

```toml
[[a]]
b = 1

[a.c]
foo = 1
```

The `a` in the second table is effectively an alias for `a[0]` (since `a` is an array-of-tables with only one element, which was the most recent one named in the document) - adding to `a[0]` in this fashion is fine since it is a regular table, not an inline one.

**Comment by marzer** [comment]
Also, your original example that you've 'verified':
```toml
a = [{ b = 1 }]
[a.c]
foo = 1
```

Is very much _not_ be legal - Since `a` is a normal array, it can't be 'appended' to as if it were a table. The online parser you've chosen would fail the `toml-test` tests methinks.

**Comment by brandonchinn178** [comment]
> The online parser you've chosen would fail the `toml-test` tests methinks.

Nope! 😄 My parser successfully parses this, and it passes the `toml-test` test suite. Sounds like I should make an issue in `toml-test`?

**Comment by marzer** [comment]
> but my parser passes the entire toml-test suite and it successfully parses this. Sounds like I should make an issue in toml-test?

Oh, exciting! Yeah. Sounds like a great idea to me.

**Comment by arp242** [comment]
Tests for appending to existing tables were added a few months ago, but I don't think there are any tests for appending to existing arrays (from my head). I'll have a look later, if someone doesn't send in a patch first (bit busy this week).

**Comment by brandonchinn178** [comment]
> tests for appending to existing arrays

There is a test for appending to inline arrays: https://github.com/BurntSushi/toml-test/blob/master/tests/invalid/array/tables-1.toml

There isn't a test for extending tables within inline arrays.

**Comment by pradyunsg** [comment]
Closing this out, since the discussion seems to have run its course.
