### ISSUE TITLE
 How to find the roadmap about toml

### ISSUE THREAD

**Issue by baoyachi** [toml-lang/toml#942]
How to find the roadmap about toml?

Roadmap or Rfc  exist? Like rust rfc : https://github.com/rust-lang/rfcs

**Comment by pradyunsg** [comment]
The TOML project doesn't have design documents that we end up having extensive discussion on -- instead, the changes are discussed in this issue tracker and pull requests for language changes in the spec serve the same purpose as rfcs.

There is also no "traditional" roadmap, since there's no established need for hte project to have such a roadmap at this time.

I'll close this out since the question has been answered. :)

**Comment by eksortso** [comment]
Even though this question's been answered officially by @pradyunsg, I'd like to suggest this [list of open issues and PRs](https://github.com/toml-lang/toml/issues/928#issuecomment-1294659512) by @ChristianSi from a few weeks back. His opinions may be his own, but I've used his list to address unresolved issues whose solutions would move us closer to a release candidate for TOML v1.1.0. It isn't a final list by any means, but it's as near a roadmap to the next release as we have for this iteration.

We can always use additional points of view by enthusiasts who want to provide their use cases and suggestions. If any of these issues, discussions, or PRs catch your eye, please feel free to drop a comment in any of these items.
