### ISSUE TITLE
Proposal: trim one new line immediately before the closing delimiter in multiline string

### ISSUE THREAD

**Issue by ZeroRin** [toml-lang/toml#969]
As a newline immediately following the opening delimiter will be trimmed, it seems reasonable to me to also trim newline in this mirrored case. 

Having `"""` or `\` at the last line of a multiline string does not seem intuitive.
For example, to represent `"Roses are red\nViolets are blue"` we should write in the following as `str1` or `str2`, but I'd argue that `str3` looks more elegant.
```toml
str1 = """
Roses are red
Violets are blue"""
str2 = """
Roses are red
Violets are blue/
"""
str3 = """
Roses are red
Violets are blue
"""
```

**Comment by ZeroRin** [comment]
In my experience final line ending in multiline text is commonly present, but rarely wanted. Like I'm always writing extra code to handle troubles caused by the last line ending.

**Comment by ZeroRin** [comment]
For displaying, most of the time an line end will be implicitly added to the string to be displayed and results in an visible empty line. For example when I try print it, or , or show it on gui with tkinter.
For holding a list of data, while text file objects can be directly iterated line by line, for a string object usually `str.split` is used, which results in an empty string at the end of the returned list if there exists a `\n` at the end, thus i need to write `obj.strip().split('\n')` for such strings.

(I mainly use python, not sure whether the these statements holds in other languages)

**Comment by arp242** [comment]
The problem here is that we can't change the existing behaviour because that would be an incompatible change; that's a non-starter. And I'm not sure if I'd be in favour of adding new syntax for this; there isn't really anything obvious and non-ugly; things like `t""" ... """` or `trim""" ... """` seems ugly.

I think this is unfortunate as I agree the current behaviour isn't great, but I'm afraid it's what we're stuck with. It does make some sense though, as in the unix world there's a long tradition that the last line of a file ends with a \n.

**Comment by arp242** [comment]
Also discussed in #827 btw, and probably a few other places.

**Comment by pradyunsg** [comment]
This would be a backwards-incompatible change to the spec _or_ involve introducing new syntax. I don't think this behaviour is worth new syntax and backwards incompatible changes are not on the table for TOML.
